# Generated by Django 3.0.5 on 2022-08-06 18:50

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220806_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to=posts.models.profile_image_path),
            preserve_default=False,
        ),
    ]
